select 
	P.LINUM,
	P.PAYMENT_DATE as PAYMENT_DATE,
	P.OSB,
	P.TEL, 
	substr(P.TEL, 10, 4) as PART_CODE,
	P.PAYMENT_ORDER, 
	P.TRANSFER_DATE, 
	P.SUM, 
	P.SETTLE_ACC,
	P.SERVICE_COMMISSION, 
	P.PAYER_COMMISSION, 
	P.RECEIVER_NUMBER, 
	P.ADDITIONAL_REQUISITES, 
	P.ROUTE,
	TR.MEM_ORDER_NUM,
	C.LINK_TYPE,
	TR.DEBET,
	TR.CREDIT 
from PAY.PAYMENTS as P
left outer join
    PAY.PAYMENTS_ACC_TR as C
    on P.LINUM = C.PAYMENTS_LINUM
    and P.TRANSFER_DATE = C.TRANSFER_DATE
left outer join
    PAY.ACCOUNTING_TRANSACTIONS as TR
    on C.ACC_TR_ID = TR.ID
where P.TEL like '30233%'
	and P.TRANSFER_DATE = ?
	and P.STATE = ?
	and P.ROUTE <> 'MANUAL'
order by PART_CODE, P.LINUM  