/*
 * Generated by nsi.perl at Mon May 25 20:23:50 2009
 */
package com.sbrf.bc.processor.multiple;

/**
 * DownloadTypes - Типы возможных выгрузок спецклиентов
 */
public interface DownloadTypes {
    /**
     * Обычная выгрузка
     */
    int NORMAL = 1;

    /**
     * Единая выгрузка для внутриотделенческих получателей
     */
    int OSB_SINGLE = 2;
}
